# Generated by Django 5.1.4 on 2025-01-25 18:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maoniapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('img', models.ImageField(blank=True, max_length=255, null=True, upload_to='pubimg/')),
                ('imgWidth', models.IntegerField(blank=True, max_length=4, null=True)),
                ('imgHeight', models.IntegerField(blank=True, max_length=4, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
