# Generated by Django 5.1.4 on 2025-01-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maoniapp', '0002_banner_alter_slide_title_alter_slide_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='img',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='url',
        ),
        migrations.AddField(
            model_name='banner',
            name='href',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='imgSrc',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pubimg/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='imgHeight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='imgWidth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
