# Generated by Django 5.1.4 on 2025-01-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maoniapp', '0004_category_href_category_imgheight_category_imgsrc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='showreview',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='business',
            name='showeval',
            field=models.BooleanField(default=True),
        ),
    ]
