# Generated by Django 5.1.4 on 2025-02-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maoniapp', '0007_language_alter_userbusiness_is_active_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='key',
            field=models.CharField(help_text="Translation key (e.g., 'welcomeMessage', 'description')", max_length=255, unique=True),
        ),
    ]
