# Generated by Django 5.1.4 on 2025-02-04 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maoniapp', '0008_alter_translation_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': 'Invitation Code', 'verbose_name_plural': 'Invitations Codes'},
        ),
    ]
