# Generated by Django 5.1.4 on 2025-02-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maoniapp', '0009_alter_code_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='key',
            field=models.CharField(help_text="Translation key (e.g., 'welcomeMessage', 'description')", max_length=255),
        ),
    ]
